services:
 postgres_database: 
  container_name: postgres_database
  image: postgres:16.3
  volumes:
    - ./docker/postgresql:/var/lib/postgresql
  ports:
    - 5432:5432
  environment:
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: finances